### ISSUE TITLE
Relative/Asolute Routes

### ISSUE THREAD

**Issue by danielhv10** [omniT/zero#4]
I'll write an script to simplify this tediuos problem.

**Comment by newrol** [comment]
There're not a lot of information around that, the only one interesting source is this:
https://gist.github.com/branneman/8048520
Although I don't like none.

One posible way I'd be an index object with all the relative routes to the program and join it as a property in the properties object

```javascript
module.exports.index = {
    app : {

}

**Comment by danielhv10** [comment]
There're not a lot of information around that, the only one interesting source is this:
https://gist.github.com/branneman/8048520
Although I don't like none.

One posible way I'd be an index object with all the relative routes to the program and join it as a property in the properties object

``` javascript
module.exports.index = {
    app : {
        src:{
            dao : {
                sigmadao : __dir +  app/src/dao/sigmadao
            }
        }
    }
}
---------------------
properties.index = ^

----------------------
var foo = requires(properties.index.app.src.dao.sigmadao);
```

**Comment by Butakus** [comment]
So in each file you just need to reach the properties file.

``` javascript
var foo = require('../../../properties').index.app.src.dao.sigmadao;
```

or

``` javascript
var index = require('../../../properties').index;
var sigmadao = require(index.app.src.dao.sigmadao);
var foobar = require(index.foo.bar);
```

Is that what you mean?

The other solution I see is to include only the base path in properties.js:

``` javascript
module.exports.index = __dirname;
```

Then in each file:

``` javascript
var index = require('../../../properties').index;
var sigmadao = require(index + 'app/src/dao/sigmadao');
var foobar = require(index + '/foo/bar');
```

Anyway, I don't see any way to avoid the require('../../../properties')

**Comment by danielhv10** [comment]
``` javascript
module.exports.index = __dirname;
```

+

We can create a symbolic link of properties.js inside the node_modules and we can import it as a library

``` javascript
require('properties');   <-- is theorical option
```

**Comment by Butakus** [comment]
Is this a practical thing? Remember that node_modules is not included in the git repository, so the link must be made by hand (or by script).

Look at this: https://gist.github.com/branneman/8048520#comment-1412502

**Comment by danielhv10** [comment]
We can create a grunt task for this kind of operations

**Comment by danielhv10** [comment]
issue possible solution in branch "relativeRoutes"

with grunt task manager client installed: (npm install -g grunt-cli) you only need to execute this command in your terminal since zero path : 'grunt build'. and a symbolic link I'll be created in the node_modules. Maybe we can add the generator sigma token file and token generator  to this task

**Comment by danielhv10** [comment]
Solved By relativeRoutes branch
